rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093


scrape_configs:
  - job_name: 'digicert_exporter'
    scrape_interval: 30m
    static_configs:
      - targets: [ 'digicert_exporter:10005' ]