name: Action - Release

on:
  workflow_call:

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: 'Craft the Changelog'
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0
      - name: "Generate CHANGELOG.md"
        uses: heinrichreimer/action-github-changelog-generator@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          onlyLastTag: true
      - name: 'Upload CHANGELOG.md'
        uses: actions/upload-artifact@v4.4.0
        with:
          name: changelog
          path: CHANGELOG.md
  release:
    runs-on: ubuntu-latest
    name: 'Publish the Release'
    needs: [ changelog ]
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0
      - name: 'Download binary artifacts'
        uses: actions/download-artifact@v4.1.8
        with:
          path: binaries
          pattern: digicert_exporter_binary_*
          merge-multiple: true
      - name: 'Download CHANGELOG artifacts'
        uses: actions/download-artifact@v4.1.8
        with:
          path: changelog
          name: changelog
      - name: 'Generate Github release'
        uses: softprops/action-gh-release@v2
        with:
          name: 'New release (${{ github.ref_name }}) ! 📦'
          body_path: changelog/CHANGELOG.md
          files: |
            binaries/*