name: Action - Go Build

on:
  workflow_call:
    inputs:
      go_version:
        description: 'The Go version used (ex: 1.21.4)'
        required: true
        type: string

jobs:
  build:
    name: 'Build'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: windows-latest
            os_small: win
            arch: amd64
          - os: ubuntu-latest
            os_small: linux
            arch: amd64
          - os: macos-latest
            os_small: darwin
            arch: amd64
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4.1.1
      - name: 'Setup Go action'
        uses: actions/setup-go@v5.0.0
        with:
          go-version: ${{ inputs.go_version }}
      - name: 'Go build (matrix)'
        run: go build -o digicert_exporter_${{ matrix.os_small }}_${{ matrix.arch }} -v
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: digicert_exporter_*