name: Workflow - Push on origin/main

on:
  push:
    branches:
      - main

jobs:
  go-lint:
    uses: ./.github/workflows/action.go.lint.yaml
    with:
      go_version: '1.22.x'
  go-test:
    uses: ./.github/workflows/action.go.test.yaml
    with:
      go_version: '1.22.x'
  go-build:
    needs: [ go-lint, go-test ]
    uses: ./.github/workflows/action.go.build.yaml
    with:
      go_version: '1.22.x'