name: Workflow - Default push

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  go-lint:
    uses: ./.github/workflows/action.go.lint.yaml
    with:
      go_version: '1.21.x'
  go-test:
    uses: ./.github/workflows/action.go.test.yaml
    with:
      go_version: '1.21.x'