name: Action - Release

on:
  workflow_call:

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: 'Craft the Changelog'
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: "Generate CHANGELOG.md"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
      - name: 'Upload CHANGELOG.md'
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: CHANGELOG.md
  release:
    runs-on: ubuntu-latest
    name: 'Publish the Release'
    needs: [ changelog ]
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: 'Download all artifacts'
        uses: actions/download-artifact@v3
      - name: 'Generate Github release'
        uses: softprops/action-gh-release@v1
        with:
          name: 'New release (${{ github.ref_name }}) ! 📦'
          body_path: changelog/CHANGELOG.md
          files: |
            binaries/*